Increment 20
KonBal/url-shortener pull request #20
Opened 2024-01-09 21:48 UTC by KonBal

2024-01-11 22:08 UTC, kilchik requested changes

2024-01-11 22:08 UTC, kilchik commented on cmd/shortener/main.go
> +	buildVersion = "N/A"
Добавь пжлст команду для сборки - либо в комментарии либо в Makefile

2024-01-12 09:42 UTC, KonBal commented on cmd/shortener/main.go
> +	buildVersion = "N/A"
добавил Makefile

2024-01-14 16:05 UTC, kilchik approved these changes

2024-01-14 20:44 UTC, merged